### ISSUE TITLE
Error with building the code

### ISSUE THREAD

**Issue by denoza** [cbeuw/GoQuiet#17]
I am trying to `make client` the code on my local machine. I cloned the repo and tried to run the command as mentioned in the README. But I got following errors, any idea how to have a clean build?

`go build -o ./build/gq-client ./cmd/gq-client
cmd/gq-client/gq-client.go:5:2: cannot find package "github.com/cbeuw/GoQuiet/gqclient" in any of:
	/usr/lib/go-1.6/src/github.com/cbeuw/GoQuiet/gqclient (from $GOROOT)
	/home/user/go/src/github.com/cbeuw/GoQuiet/gqclient (from $GOPATH)
cmd/gq-client/gq-client.go:6:2: cannot find package "github.com/cbeuw/GoQuiet/gqclient/TLS" in any of:
	/usr/lib/go-1.6/src/github.com/cbeuw/GoQuiet/gqclient/TLS (from $GOROOT)
	/home/user/go/src/github.com/cbeuw/GoQuiet/gqclient/TLS (from $GOPATH)
Makefile:4: recipe for target 'client' failed
make: *** [client] Error 1
`

**Comment by cbeuw** [comment]
You didn't have github.com/cbeuw/GoQuiet in your $GOPATH. Try 
`go get github.com/cbeuw/GoQuiet`
first, and then navigate to GoQuiet to use `make`

**Comment by denoza** [comment]
It worked. Thanks!

Closing.
