### ISSUE TITLE
fatal error: runtime.SetFinalizer: pointer not in allocated block

### ISSUE THREAD

**Issue by kimw** [cbeuw/GoQuiet#23]
https://gist.github.com/kimw/90d5ec06175c33f4bbb1cfd5c7261672

**Comment by cbeuw** [comment]
How often does this occur? Do you have any method to reproduce?

This seems to be a side effect of the [pointer hack](https://github.com/cbeuw/gotfo/blob/e8588a8e0499d45affbdedf940842dbfb2805cd0/util.go#L73).

**Comment by kimw** [comment]
Seems that it's disappeared in these days. Close this issue.
