### ISSUE TITLE
Client crash when server setting are changed

### ISSUE THREAD

**Issue by johnx7271** [cbeuw/GoQuiet#25]
I changed the server setting for gq-server: FastOpen, but then the client crashed.
When the internet connection temporarily goes off, it also crashes.

Proposition: The client should be more stable, and should not be affected by server side's change.

**Comment by cbeuw** [comment]
Could you provide the crash log?

**Comment by yhwfr1** [comment]
大约每隔1小时或更多一些时间出错，以下是nohup.out的记录,

goroutine 35104 [syscall, 1 minutes]:
syscall.Syscall(0x0, 0x35, 0xc42092c800, 0x2800, 0xc420623080, 0xc42033e578, 0x483b80)
	/usr/lib/go-1.9/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x35, 0xc42092c800, 0x2800, 0x2800, 0xc42033e500, 0x0, 0x0)
	/usr/lib/go-1.9/src/syscall/zsyscall_linux_amd64.go:756 +0x55
syscall.Read(0x35, 0xc42092c800, 0x2800, 0x2800, 0xc420805280, 0x4, 0xc42033e600)
	/usr/lib/go-1.9/src/syscall/syscall_unix.go:162 +0x49
internal/poll.(*FD).Read(0xc4201c4700, 0xc42092c800, 0x2800, 0x2800, 0x0, 0x0, 0x0)
	/usr/lib/go-1.9/src/internal/poll/fd_unix.go:122 +0x125
net.(*netFD).Read(0xc4201c4700, 0xc42092c800, 0x2800, 0x2800, 0x10200000000, 0x0, 0xc42092c800)
	/usr/lib/go-1.9/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000e320, 0xc42092c800, 0x2800, 0x2800, 0x0, 0x0, 0x0)
	/usr/lib/go-1.9/src/net/net.go:176 +0x6d
io.ReadAtLeast(0x7efd098fc080, 0xc42000e320, 0xc42092c800, 0x2800, 0x2800, 0x1, 0x0, 0xe0, 0x0)
	/usr/lib/go-1.9/src/io/io.go:309 +0x86
main.(*ssPair).serverToRemote(0xc42000c3c0)
	/home/andy/go/src/github.com/cbeuw/GoQuiet/cmd/gq-server/gq-server.go:81 +0xdd
created by main.dispatchConnection.func2
	/home/andy/go/src/github.com/cbeuw/GoQuiet/cmd/gq-server/gq-server.go:114 +0x115
 2018-03-26 04:53:50 ERROR: plugin service exit unexpectedly

**Comment by cbeuw** [comment]
@yhwfr1 
丢出来的fatal error是什么？

**Comment by yhwfr1** [comment]
服务器端每隔1、2个小时就退出。以下是nohup.out里的记录，

goroutine 53602 [syscall, 1 minutes]:
syscall.Syscall(0x0, 0x14, 0xc420752000, 0x2800, 0xc4200c3c80,
0xc4209bcd78, 0x483b80)
/usr/lib/go-1.9/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x14, 0xc420752000, 0x2800, 0x2800, 0xc4209bcd00, 0x0, 0x0)
/usr/lib/go-1.9/src/syscall/zsyscall_linux_amd64.go:756 +0x55
syscall.Read(0x14, 0xc420752000, 0x2800, 0x2800, 0xc42069a200, 0x4,
0xc4209bce00)
/usr/lib/go-1.9/src/syscall/syscall_unix.go:162 +0x49
internal/poll.(*FD).Read(0xc42069a880, 0xc420752000, 0x2800, 0x2800, 0x0,
0x0, 0x0)
/usr/lib/go-1.9/src/internal/poll/fd_unix.go:122 +0x125
net.(*netFD).Read(0xc42069a880, 0xc420752000, 0x2800, 0x2800,
0x10200000000, 0x0, 0xc420752000)
/usr/lib/go-1.9/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000e0b8, 0xc420752000, 0x2800, 0x2800, 0x0, 0x0, 0x0)
/usr/lib/go-1.9/src/net/net.go:176 +0x6d
io.ReadAtLeast(0x7f4fdb293080, 0xc42000e0b8, 0xc420752000, 0x2800, 0x2800,
0x1, 0x0, 0x500, 0x0)
/usr/lib/go-1.9/src/io/io.go:309 +0x86
main.(*ssPair).serverToRemote(0xc42000c140)
/home/andy/go/src/github.com/cbeuw/GoQuiet/cmd/gq-server/gq-server.go:81
+0xdd
created by main.dispatchConnection.func2
/home/andy/go/src/github.com/cbeuw/GoQuiet/cmd/gq-server/gq-server.go:114
+0x115

goroutine 53814 [syscall]:
syscall.Syscall(0x0, 0x13, 0xc420833000, 0x2800, 0xc420611200,
0xc4205d0d78, 0x483b80)
/usr/lib/go-1.9/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x13, 0xc420833000, 0x2800, 0x2800, 0xc4205d0d00, 0x0, 0x0)
/usr/lib/go-1.9/src/syscall/zsyscall_linux_amd64.go:756 +0x55
syscall.Read(0x13, 0xc420833000, 0x2800, 0x2800, 0xc42069ac80,
0xc420611200, 0xc4205d0e00)
/usr/lib/go-1.9/src/syscall/syscall_unix.go:162 +0x49
internal/poll.(*FD).Read(0xc42069b280, 0xc420833000, 0x2800, 0x2800, 0x0,
0x0, 0x0)
/usr/lib/go-1.9/src/internal/poll/fd_unix.go:122 +0x125
net.(*netFD).Read(0xc42069b280, 0xc420833000, 0x2800, 0x2800,
0x10200000000, 0x0, 0xc420833000)
/usr/lib/go-1.9/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000e160, 0xc420833000, 0x2800, 0x2800, 0x0, 0x0, 0x0)
/usr/lib/go-1.9/src/net/net.go:176 +0x6d
io.ReadAtLeast(0x7f4fdb293080, 0xc42000e160, 0xc420833000, 0x2800, 0x2800,
0x1, 0x0, 0x900, 0x0)
/usr/lib/go-1.9/src/io/io.go:309 +0x86
main.(*ssPair).serverToRemote(0xc42000c2e0)
/home/andy/go/src/github.com/cbeuw/GoQuiet/cmd/gq-server/gq-server.go:81
+0xdd
created by main.dispatchConnection.func2
/home/andy/go/src/github.com/cbeuw/GoQuiet/cmd/gq-server/gq-server.go:114
+0x115
 2018-03-26 14:12:36 ERROR: plugin service exit unexpectedly

2018-03-26 23:10 GMT+08:00 Qian Wang <notifications@github.com>:

**Comment by johnx7271** [comment]
I was talking about the client side.
There is very little in the log, the only log I found is by ss-local, nothing for gq-client-plugin.
The client I use is the shadowsocks-libev version.

**Comment by cbeuw** [comment]
@kimw @johnx7271 @yhwfr1 
I couldn't reproduce your crashes but I believe it's a memory leak. I changed some [suspicous code](https://github.com/cbeuw/gotfo/commit/96ff530acaa3b0a453806e639f5ff0e99c2194d0) and released a new version, but again I have no way of tesing if this is actually fixed.

**Comment by yhwfr1** [comment]
服务器内存溢出的问题在1.1.2里已经解决，谢谢！
