### ISSUE TITLE
这个可以达到v2ray中websocket+tls+Nginx一样?

### ISSUE THREAD

**Issue by wclmgcd** [cbeuw/GoQuiet#3]
小白如上

**Comment by cbeuw** [comment]
主要区别在于v2ray支持完整的tls握手，目前GoQuiet只支持session resumption。不过这意味着使用v2ray需要自己拥有域名。优点是看上去更真实，缺点是被发现后这个域名就废了。

GoQuiet可以把你的服务器伪装成一个别的网站的服务器，比如在默认配置文件里就是伪装成bing的。GFW明显不会封bing的域名，而他们查bing的DNS记录之后才能知道你的IP不属于bing，但这也不是100%肯定

**Comment by wclmgcd** [comment]
感谢解答,我的ip被封,现在就websocket+tls+Nginx+cloudflare救命,可是最近看YouTube总被限速.v2ray不方便的一点就是路由器上不可使用.这个插件可以支持openwrt吗

**Comment by cbeuw** [comment]
v2ray也是go写的吧，go交叉编译很方便。如果路由器能不能用v2ray是因为gc不支持路由器的指令集，那这个插件也不行；如果是因为内存占用，那这个插件的内存占用很少，应该能用

**Comment by cbeuw** [comment]
请见 #7
