### ISSUE TITLE
gq-server 1.1.1+ IPv6 not working

### ISSUE THREAD

**Issue by zmz125000** [cbeuw/GoQuiet#42]
ss+ipv6 works.
ss+goquiet+ipv6, client side using ipv4 works.
ss+goquiet+ipv6, client side using ipv6 doesn't work, log is empty.
ss+goquiet+ipv6, client side using ipv6 without goquite, logs show 
`2018/11/23 00:03:16 gq-server.go:132: +1 non SS non (or malformed) TLS traffic from [aaaa]:53174`

ss+goquiet+ipv6 netstat
```
tcp        0      0 127.0.0.1:11277         0.0.0.0:*               LISTEN      4144/ss-server
tcp6       0      0 :::443                  :::*                    LISTEN      4145/gq-server
```

config file
```
{
        "server":"::0",
        "server_port":443,
        "password":"",
        "timeout":600,
        "method":"chacha20-ietf-poly1305",
        "fast_open":true,
        "reuse_port":true,
        "no_delay":true,
        "mode":"tcp_and_udp",
        "plugin":"gq-server",
        "plugin_opts":"WebServerAddr=204.79.197.200:443;Key=;FastOpen=true"
}
```

**Comment by zmz125000** [comment]
#22 
@k432ts does IPv6 work for you now?

**Comment by k432ts** [comment]
I'm afraid it's still not working. I just stopped using this plugin.

**Comment by chenshaoju** [comment]
Actually, This plugin IPv6 is working.

Make sure you are configuring is right.

In Shadowsocks-libev configure, Server must be `::`, And make sure sysctl.conf is allowed to bind IPv6 and IPv4. `net.ipv6.bindv6only=0`

![default](https://user-images.githubusercontent.com/515763/50043068-ab4d8200-00a8-11e9-998d-3b66bd7b1837.png)

**Comment by zmz125000** [comment]
@k432ts @chenshaoju 
chenshaoju's configuration works.
