### ISSUE TITLE
Compile mips32 with softfloat to run on routers without fpu

### ISSUE THREAD

**Issue by rwasef1830** [cbeuw/GoQuiet#45]
Hello,
The released mips32 doesn't work on MIPS 24kc processor (mips32r2) because it doesn't have FPU and requires compile with softfloat support. It gives invalid instruction error and crashes on router like GL inet ar300m.

Could you release such a binary ? Thanks in advance.

**Comment by cbeuw** [comment]
I'm pretty ignorant when it comes architectures so I'm not sure what exactly the softfloat is. But reading around it appears that I only need to set the GOMIPS=softfloat for go build? I did that and I uploaded gq-client-linux-mips_softfloat-1.2.2 in releases. Hope that works

**Comment by rwasef1830** [comment]
New binary works fine thank you.
