### ISSUE TITLE
is it the log?

### ISSUE THREAD

**Issue by malikshi** [cbeuw/GoQuiet#47]
![screenshot_717](https://user-images.githubusercontent.com/9080737/52562032-bf56fb00-2e2f-11e9-8552-d73a78d83761.png)
speed went down?

**Comment by cbeuw** [comment]
The ones with the pink timestamp are generated by Shadowsocks, not GoQuiet. See https://github.com/shadowsocks/shadowsocks-libev/issues/1811 may help you

**Comment by cbeuw** [comment]
Though it's possible that GoQuiet crashed. Please try to run GoQuiet in standalone mode and get its stack trace if that happens

**Comment by malikshi** [comment]
thanks, i will try using standalone mode,

**Comment by malikshi** [comment]
> Though it's possible that GoQuiet crashed. Please try to run GoQuiet in standalone mode and get its stack trace if that happens

@cbeuw starting gqserver first then ss server, and ss server seem says port already in use. im checking its using by gq-server.

**Comment by malikshi** [comment]
![screenshot_720](https://user-images.githubusercontent.com/9080737/52567777-a6564600-2e3f-11e9-894e-caef2f7acc64.png)
thanks, sir, it's working. I was wondering 10 min what's wrong. ah its wrong path gqserver.json LUL
