### ISSUE TITLE
The latest version of the binary is not available on mipsle.

### ISSUE THREAD

**Issue by loyess** [cbeuw/GoQuiet#48]
V1.2.1 version is used normally.

I tried to compile the latest version with xgo. The test result is that the binary file still cannot be executed. I don't know where the error is. Can you fix the latest version?

**Comment by cbeuw** [comment]
There are released mipsle binaries for v1.2.2.

My bet for the binary problem is due to the lack of floating point instruction support. What CPU model are you using?

**Comment by loyess** [comment]
I am using it on the router. The result of the uname -m command is mips, but the actual executable binary file is mipsle. I have tried all the mips binary files that you posted, and all of them cannot be executed.

**Comment by loyess** [comment]
I don't understand why your previous version of the binary can be used, but the latest version does not.

**Comment by loyess** [comment]
Has been solved, is the reason for the lack of floating point instruction set, thank you
