### ISSUE TITLE
OpenWRT/Lede

### ISSUE THREAD

**Issue by m4niacjp** [cbeuw/GoQuiet#7]
Any idea on how to build for Lede/Openwrt?

**Comment by cbeuw** [comment]
If your router uses 32bit ARM CPU, you can use the ARM binaries out of the box. If it uses MIPS, then you need to build a cross compiling gccgo tool chain. I'll give it a try but I will very likely give up because I never enjoyed dependency shenanigans.

**Comment by cbeuw** [comment]
I have added a binary for mips32: https://github.com/cbeuw/GoQuiet/releases
Please tell me if it works once you tried it because I have no way of testing it

**Comment by m4niacjp** [comment]
Sorry my router is a IPQ8068 ARMv7 64bit core. I'll try now with your linuxarm-1.0.0 version.

**Comment by m4niacjp** [comment]
I'm trying to build and OpenWRT/LEDE package, any dependencies required for building?

**Comment by cbeuw** [comment]
No, this plugin uses no packages beyond the standard library

**Comment by linusyang** [comment]
I rewrote (or naïvely translated, one could say that) GoQuiet client [into C](https://github.com/linusyang92/shadowsocks-libev/blob/ssr/src/libgoquiet.c) which may help port it to embedded devices. If you are too lazy to rewrite a new C client like me, there is a [modified SSR libev client](https://github.com/linusyang92/shadowsocks-libev/tree/ssr#run-as-sip003-plugin) that can be used as a drop-in replacement of `gq-client` that serves as an SIP003 plugin with GoQuiet protocol.

**Comment by m4niacjp** [comment]
What about SS-libev?

**Comment by qiwihui** [comment]
@cbeuw Is there a newest binary for mips32? I would like to test it on openwrt.

**Comment by cbeuw** [comment]
@qiwihui I have added the binary for mips32
